[phases.setup]
commands = [
  "apt-get update && apt-get install -y maven",
  "cd railway-backend && mvn clean package"
]

[phases.build]
commands = ["echo Build phase completed"]

[phases.start]
commands = ["java -jar railway-backend/target/*.jar"]
